#!/usr/bin/env python3
"""Build the single-file adapter from package-manifest.toml."""

from __future__ import annotations

import argparse
import os
import re
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from tree_layout import SUITE, require_repository_root  # noqa: E402

# The knowledge sources are the suite's. The manifest is the repository's.
ROOT = SUITE


def load_manifest(root: Path | None = None) -> dict:
    with ((root or require_repository_root()) / "package-manifest.toml").open("rb") as handle:
        return tomllib.load(handle)


def slug(text: str) -> str:
    text = text.strip().casefold()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    return re.sub(r"[\s-]+", "-", text).strip("-")


def rewrite_local_links(
    text: str,
    root: Path,
    *,
    source_rel: str,
    output_rel: str,
    included_sources: set[str],
) -> str:
    """Rewrite repository-relative links for the generated adapter's actual location.

    Markdown sources live in several directories. A relative link that is valid
    in its source file may be invalid after the source is flattened into
    ``adapters/``. Links to Markdown sources included in the flat document
    become internal anchors. Other existing repository targets are rebased relative
    to the adapter output file.
    """
    pattern = re.compile(r"(!?)\[([^\]]*)\]\(([^)]+)\)")
    source_path = (root / source_rel).resolve()
    output_path = (root / output_rel).resolve()

    def resolve_target(raw_path: str) -> Path | None:
        candidates = [source_path.parent / raw_path, root / raw_path]
        for candidate in candidates:
            resolved = candidate.resolve()
            try:
                resolved.relative_to(root.resolve())
            except ValueError:
                continue
            if resolved.exists():
                return resolved
        return None

    def replace(match: re.Match[str]) -> str:
        image_prefix, label, raw = match.groups()
        target_text = raw.strip()
        lowered = target_text.casefold()
        if (
            not target_text
            or target_text.startswith("#")
            or lowered.startswith(("http://", "https://", "mailto:", "data:"))
        ):
            return match.group(0)

        path_part, separator, fragment = target_text.partition("#")
        target = resolve_target(path_part)
        if target is None:
            return match.group(0)

        rel_from_root = target.relative_to(root.resolve()).as_posix()
        if target.is_file() and target.suffix.casefold() == ".md" and rel_from_root in included_sources:
            if fragment:
                rewritten = f"#{fragment}"
            else:
                heading = next(
                    (
                        line[2:].strip()
                        for line in target.read_text(encoding="utf-8").splitlines()
                        if line.startswith("# ")
                    ),
                    target.stem,
                )
                rewritten = f"#{slug(heading)}"
        else:
            relative = Path(os.path.relpath(target, output_path.parent)).as_posix()
            if target.is_dir() and raw.rstrip().endswith("/"):
                relative += "/"
            rewritten = relative + (f"#{fragment}" if separator else "")
        return f"{image_prefix}[{label}]({rewritten})"

    return pattern.sub(replace, text)


def flat_config(manifest: dict) -> tuple[str, list[str]]:
    cfg = manifest["flat"]
    output = cfg["output"]
    sources = cfg["sources"]
    if not isinstance(output, str) or not isinstance(sources, list) or not sources:
        raise ValueError("flat must define output and non-empty sources")
    if sources[0] != "SKILL.md":
        raise ValueError("flat.sources must begin with SKILL.md")
    return output, sources


def render(root: Path = ROOT, manifest: dict | None = None) -> str:
    manifest = manifest or load_manifest()
    output_rel, sources = flat_config(manifest)

    chunks: list[str] = []
    for index, rel in enumerate(sources):
        path = root / rel
        if not path.is_file():
            raise FileNotFoundError(path)
        content = rewrite_local_links(
            path.read_text(encoding="utf-8"),
            root,
            source_rel=rel,
            output_rel=output_rel,
            included_sources=set(sources),
        ).rstrip()
        if index == 0:
            chunks.append(content)
            chunks.append(
                "\n\n<!-- Generated flat adapter. Source order is defined in "
                "package-manifest.toml. Do not edit this file directly. -->"
            )
        else:
            chunks.append(f"\n\n---\n\n<!-- Source: {rel} -->\n\n{content}")
    return "".join(chunks) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated adapter is stale")
    parser.add_argument("--stdout", action="store_true", help="write the generated content to stdout")
    args = parser.parse_args(argv)

    manifest = load_manifest()
    output_rel, _ = flat_config(manifest)
    output = ROOT / output_rel
    content = render(ROOT, manifest)

    if args.stdout:
        sys.stdout.write(content)
        return 0

    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != content:
            print(f"stale generated adapter: {output_rel}", file=sys.stderr)
            return 1
        print(f"adapter is current: {output_rel} ({len(content.encode('utf-8')):,} bytes)")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {output_rel} ({len(content.encode('utf-8')):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
